version: '3.7'
services:
  backend:
    build:
      context: backend-python/
      dockerfile: Dockerfile
    networks:
    - application
    ports:
    - "9090:8080"
    depends_on:
    - mongodb

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass12345
    ports:
    - "27017:27017"
    networks:
    - application
    volumes:
    - mongodata:/data/db
  mongo-express:
    image: mongo-express
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongodb
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    - ME_CONFIG_MONGODB_ADMINUSERNAME=root
    - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
    - ME_CONFIG_BASICAUTH_USERNAME=admin
    - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    volumes:
    - mongodata
    depends_on:
    - mongodb
    healthcheck:
      test:  wget --quiet --tries=3 --spider http://admin:admin123@10.10.10.60:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
    - application
    ports:
    - "8081:8081"
    restart: always
      
networks:
   application:
     name: application

volumes:
  mongodata:
    name: mongodata